
name: cashier_system
description: "cashier system created by MR-ROBOT company"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  #! Flutter Get state management
  get: ^4.6.6
  device_info_plus: ^10.0.0

  #! Data Persistence
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  #! HTTP Requests
  http: ^1.2.0

  #! Internationalization
  intl: ^0.19.0

  #! Responsive Design
  flutter_screenutil: ^5.9.0
  window_manager: ^0.4.2

  #! Image / Icons / SVG
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.3.1

  #! Widgets
  drop_down_list: ^0.0.5
  file_picker: ^8.0.0+1
  flutter_simple_calculator: ^2.2.5
  menu_button: ^1.4.2+1

  #! Designing
  google_fonts: ^6.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  # flutter_local_notifications: ^17.1.2

  dropdown_search: ^5.0.6
  image_picker: ^1.1.2
  #! Printing
  sunmi_printer_plus: ^2.1.3
  printing: ^5.9.2
  screenshot: ^1.3.0
  pdf: ^3.3.0
  process: ^4.2.4
  open_file: ^3.5.5
  flutter_colorpicker: ^1.0.3
  barcode: ^2.2.8
  barcode_widget: ^2.0.4
  flutter_barcode_listener: ^0.1.4
  visibility_detector: ^0.4.0+2
  flutter_localizations:
    sdk: flutter
  # excel: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ferminus_logo.png"
  min_sdk_android: 21

  windows:
    generate: true
    image_path: "assets/app_icon.ico"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/ferminus_logo.png"
flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/lottie/
    - assets/cashier_system.db
    - assets/fonts/Barlow/Barlow-Regular.ttf
    - assets/fonts/Noto_Kufi_Arabic/static/NotoKufiArabic-Bold.ttf
    - assets/fonts/Noto_Kufi_Arabic/static/NotoKufiArabic-Regular.ttf
